HTTP/1.0 200 OK
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<head>
    <title>Mantrid Test Page</title>
    <style>
        body {
            font-family: sans-serif;
        }
        .footer {
            color: #aaa;
            border-top: 1px solid #aaa;
            padding: 5px 0 0 0;
            margin: 20px 0 0 0;
            font-size: 70%;
        }
    </style>
</head>
<body>
    <h1>Mantrid Test Page</h1>
    <p>
    Congratulations; if you can see this, Mantrid is successfully serving requests.
    </p>
    <div class="footer">Powered by Mantrid</div>
</body>
</html>
